baseurl = "http://thinkingco.de"
languageCode = "en-us"
title = "Ex chaos simplicitas - Thinking Code"

canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Ex chaos simplicitas"
  author = "Tommaso Patrizi"

[[menu.main]]
    name = "Tech Blog"
    pre = "<i class='fa fa-download'></i>"
    url = "/techblog/"
    weight = -200
[[menu.main]]
    name = "Notes"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/notes/"
    weight = -180
[[menu.main]]
    name = "Portfolio"
    pre = "<i class='fa fa-comments'></i>"
    url = "/portfolio/"
    weight = -150
[[menu.main]]
    name = "Other Topics"
    pre = "<i class='fa fa-heart'></i>"
    url = "/blog/"
    weight = -110
